variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  SITE_BUCKET: $S3_SITE_BUCKET
  CLOUDFRONT_DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID

stages:
  - build
  - deploy
  # - test

cache:
  paths:
    - node_modules/

build:
  image: node:latest
  stage: build
  script:
    - yarn install
    - yarn release
  artifacts:
    expire_in: 1 week
    paths:
      - build

# test:
#   stage: test
#   script:
#     - echo "Running react test suite......"

deploy:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest # see the note below
  stage: deploy
  script:
    - aws s3 cp build s3://$SITE_BUCKET --recursive --cache-control max-age=31536000,public --acl public-read --exclude index.html
    - aws s3 cp build/index.html s3://$SITE_BUCKET/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read
    - aws s3 sync build s3://$SITE_BUCKET --delete
  only:
    - master
